### PR TITLE
React 17 in peerDependencies

### PR DESCRIPTION
**Pull request by superpav**
Just a simple change to resolve warning in #139

### CODE REVIEW

**Comment by pablosichert** [comment]
Thank you!

**Comment by fabn** [comment]
@pablosichert Any chance to have this on NPM?

**Comment by Hyperkid123** [comment]
@pablosichert can we get this released? If you try installing the latest version with react 17 and npm@7 strict mode, you will get an invalid dependency version error. :slightly_smiling_face:

**Comment by pmartin35** [comment]
@pablosichert any chance you can release this change?

**Pull request merged**
