### PR TITLE
Bugfix: conditional check around ellipsis removal to prevent errors in unexpected situations

### LINKED ISSUE #128: ComponentWillUnmount ellipsis removal fails in test suites and other situations
In `ComponentWillUnmount`, `this.ellipsis` and `this.ellipsis.parentNode` need to be checked for before attempting removal so that it does not fail in test suites or other situations where it no longer exists. I will submit a PR for this simple fix shortly.

### PR DESCRIPTION
**Pull request by kevinparkerson**
Fixes #128

Adds a conditional check around ellipsis removal in `ComponentWillUnmount` to help pass test suites and other situations where it might be missing

### CODE REVIEW

**Comment by kevinparkerson** [comment]
@pablosichert thank you so much for this component! It is extremely useful and I've found it more reliable than other options 👍 I'm sure you're quite busy but hopefully you'll have some time to merge this simple PR so it is integrates with testing suites without mocks

**Comment by pablosichert** [comment]
Hey there! Sounds fair enough to include that check.

I'm still curious when that happens, could you elaborate?

**Comment by kevinparkerson** [comment]
@pablosichert it was occurring when running Jest / Storybook tests, likely due to its use of JSDOM instead of a real browser environment. There's likely a way to create a mock or workaround for this issue, but having this simple check makes it easier to integrate right away.

Additionally I've seen the same `Cannot read property 'parentNode' of undefined` error in the console from time to time when visiting a different page in a Next.js app.

**Comment by pablosichert** [comment]
If it only happened for the tests, I would have considered to detect that at instantiation.

But with the risk of it happening at runtime, applying the check there seems like the better option.

Thank you for the PR!

**Comment by kevinparkerson** [comment]
@pablosichert No problem! Thank you for the quick review and merge!

**Pull request merged**
