### PR TITLE
Fix infinite loop over non-visible elements

### PR DESCRIPTION
**Pull request by jordie23**
Fixes issue where if an element is hidden on the page, react-truncate will infinitely loop calling requestAnimationFrame taking up CPU. 

Solution is: If the target's parent isn't visible, don't try to calculate its width.

If there's a better solution, please feel free to comment, adjust commits.

Fixes issue #61

### CODE REVIEW

**Comment by jordie23** [comment]
I'm not overly happy with the test as I had to add 'isVisible' to the component for it to test it. 

@PabloSichert as you're more familiar with the code, perhaps you know a better way. I haven't used 'unexpected' much before, just enzyme for react testing.

**Comment by jordie23** [comment]
@PabloSichert This was updated to use the current target instead of parent

**Comment by jordie23** [comment]
Is this likely to be merged at all?

**Comment by moubi** [comment]
@jordie23 can you clarify what do you mean by _"hidden on the page"_ - hidden with css using let's say `display: none` or just not scrolled to the view?

**Comment by jordie23** [comment]
Hidden with css `display: none `, for example on a responsive page.

**Comment by moubi** [comment]
Ok, that was good to know. 

I suggest to continue with these steps:
1. prove the fail case first by adding test for the infinite loop of requestAnimationFrame. 
2. then finish the solution you are proposing.

Are you fine with that approach?

**Pull request closed without merging**
